#+TITLE: My nix-darwin/NixOS configuration

Welcome to my nix-home.
The goal for this repo is to delcaratively manage my MacOS/NixOS Using nixos/[[https://github.com/LnL7/nix-darwin][nix-darwin]] and [[https://github.com/nix-community/home-manager][home-manger]].

I feel like MacOS side's setup is pretty stable, feel free to take what you like.

* Inspirations
- https://github.com/cmacrae/config (nix-darwin)
- https://github.com/hlissner/dotfiles/ (NixOS)
- https://github.com/jwiegley/nix-config

| Shell    | zsh + starship   |
|----------+------------------|
| WM       | yabai + spacebar |
| Terminal | Alacritty        |
| Edtior   | Doom Emacs       |


* MacOS
** Install

**** Install single-user Nix

#+begin_src sh
sh <(curl https://nixos.org/nix/install)
#+end_src
**** Latest OS and the workaround
https://www.philipp.haussleiter.de/2020/04/fixing-nix-setup-on-macos-catalina/
**** Install flake
**** Install brew (sin)
there are lots of GUI programs, we cannot install nicely using pure nix. There is brew-module in nix-darwin.
What is benefits of this ?
we can install/uninstall applications using nix
don't forget to do
~brew analytics off~

** [[https://github.com/LnL7/nix-darwin#updating][Update]]

#+BEGIN_SRC shell
nix flake update --recreate-lock-file
#+END_SRC

** build on macos?
~nix build .#yuan-mac~
*** switch ?
~./result/sw/bin/darwin-rebuild switch --flake .~



* Caveats
** ~fontconfig~ doesn't work for MacOS ?
** Exclude Nix directory from Spotlight index
** single-user nix-darwin permission issue
~sudo chown -R yuanwang:staff /nix/store~

