#+TITLE: My nix-darwin/NixOS configuration

Welcome to my nix-home.
The goal for this repo is to delcaratively manage my MacOS/NixOS Using nixos/[[https://github.com/LnL7/nix-darwin][nix-darwin]] and [[https://github.com/nix-community/home-manager][home-manger]].

I feel like MacOS side's setup is pretty stable, feel free to take what you like.

* Current MacOS setup
| Shell    | zsh + starship   |
|----------+------------------|
| WM       | yabai + spacebar |
| Terminal | Alacritty + tmux |
| Edtior   | Doom Emacs       |


* Inspirations
- https://github.com/cmacrae/config (nix-darwin)
- https://github.com/hlissner/dotfiles/ (NixOS)
- https://github.com/jwiegley/nix-config

* MacOS
** Install

**** Install Nix (with daemon)

I think nix with daemon is recommended over the single user mode.

~sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume~
**** Turn on flake
edit ~/etc/nix/nix.conf~

~experimental-features = nix-command flakes~
**** Install brew (sin)
there are lots of GUI programs, we cannot install nicely using pure nix. There is brew-module in nix-darwin.
What is benefits of this ?
we can install/uninstall applications using nix
don't forget to do
~brew analytics off~

** [[https://github.com/LnL7/nix-darwin#updating][Update]]

#+BEGIN_SRC shell
nix flake update --recreate-lock-file
#+END_SRC

** build on macos?
~nix build .#yuan-mac~
*** switch ?
~./result/sw/bin/darwin-rebuild switch --flake .~



* Caveats
** ~fontconfig~ doesn't work for MacOS ?
** Exclude Nix directory from Spotlight index
** single-user nix-darwin permission issue
~sudo chown -R yuanwang:staff /nix/store~

