{ pkgs, lib }:

let
  featureLib = import ../modules/editor/emacs/nima/lib/feature.nix { inherit lib; };

  sampleEl = builtins.toFile "sample.el" ''
    ;;; sample.el --- Sample feature -*- lexical-binding: t; -*-
    (message "sample feature loaded")
  '';

  generated =
    (featureLib.mkElispFeature {
      name = "sample";
      file = sampleEl;
    }).elisp;

  generatedNoFooter =
    (featureLib.mkElispFeature {
      name = "sample-no-footer";
      file = sampleEl;
      footer = false;
    }).elisp;
in
assert featureLib.mkFeatureSymbol "sample" == "nima-feature-sample";
assert lib.hasInfix "sample feature loaded" generated;
assert lib.hasInfix ";;;; sample -- generated by nix-home nima feature helper" generated;
assert lib.hasInfix "(provide 'nima-feature-sample)" generated;
assert !(lib.hasInfix "(provide 'nima-feature-sample-no-footer)" generatedNoFooter);
pkgs.runCommand "nima-feature-helper-test"
  { meta.description = "Regression tests for nima feature helper"; }
  ''
      mkdir -p "$out"
      cat > "$out/generated.el" <<'EOF'
    ${generated}
    EOF
  ''
