# DGX Spark hardware configuration
# This file was generated by 'nixos-generate-config' and adapted for
# the DGX Spark (ARM64). Update UUIDs after running nixos-generate-config.
{ lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "usb_storage"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # DGX Spark uses ARM64
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
