{ lib }:

let
  inherit (lib) optionalString;

  vars = import ./elisp-vars.nix { inherit lib; };

  mkFeatureSymbol = name: "nima-feature-${name}";
in
{
  inherit mkFeatureSymbol;

  mkElispFeature =
    {
      name,
      file,
      epkgs ? (_epkgs: [ ]),
      overlay ? (_final: _prev: { }),
      order ? 0,
      enable ? true,
      header ? true,
      footer ? true,
      defvar ? { },
      setq ? { },
      extraElisp ? "",
    }:
    {
      inherit
        enable
        epkgs
        overlay
        order
        ;

      elisp = ''
        ${optionalString header ";;;; ${name} -- generated by nix-home nima feature helper"}

        ${vars.mkDefvars defvar}
        ${vars.mkSetq setq}

        ${builtins.readFile file}

        ${extraElisp}

        ${optionalString footer "(provide '${mkFeatureSymbol name})"}
      '';
    };
}
