#!/usr/bin/env python3
"""Regenerate modules/private/_sources/generated.nix from generated.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def emit_entry(name: str, entry: dict) -> str:
    src = entry["src"]
    passthru = entry.get("passthru") or {}
    lines = [
        f"  {name} = {{",
        f'    pname = "{entry.get("name", name)}";',
        f'    version = "{entry["version"]}";',
        "    src = fetchgit {",
        f'      url = "{src["url"]}";',
        f'      rev = "{src["rev"]}";',
        f"      fetchSubmodules = {str(src.get('fetchSubmodules', False)).lower()};",
        f"      deepClone = {str(src.get('deepClone', False)).lower()};",
        f"      leaveDotGit = {str(src.get('leaveDotGit', False)).lower()};",
        "      sparseCheckout = [ ];",
        f'      sha256 = "{src["sha256"]}";',
        "    };",
    ]

    if update_script := passthru.get("updateScript"):
        lines.append(f'    updateScript = "{update_script}";')

    if tag := passthru.get("tag"):
        lines.append("    passthru = {")
        lines.append(f'      tag = "{tag}";')
        lines.append("    };")

    lines.append(f'    date = "{entry["date"]}";')
    lines.append("  };")
    return "\n".join(lines)


def main() -> None:
    json_path = Path(sys.argv[1])
    nix_path = Path(sys.argv[2])
    data = json.loads(json_path.read_text())

    body = "\n".join(emit_entry(name, data[name]) for name in sorted(data))
    nix_path.write_text(
        "# This file was generated by nvfetcher, please do not modify it manually.\n"
        "{\n"
        "  fetchgit,\n"
        "}:\n"
        "{\n"
        f"{body}\n"
        "}\n"
    )


if __name__ == "__main__":
    main()
