name: "build"
on:
  pull_request:
  push:
jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: yuanwang-wf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    #https://github.com/github/roadmap/issues/528
    - run: nix build .#ci
