name: "build"
on:
  pull_request:
  push:
jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v7
    - uses: cachix/cachix-action@v12
      with:
        name: yuanwang-wf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    #https://github.com/github/roadmap/issues/528
    - run: nix flake check
  nixos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: yuanwang-wf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: yuanwang-wf,nix-community
    - run: nix --version
