name: "build"
on:
  pull_request:
  push:
jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: yuanwang-wf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#wf17084
  nixos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: yuanwang-wf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: yuanwang-wf,nix-community
    - run: nix build .#asche -L
