
name: Update flake

on:
  schedule:
    # every sunday at 8am UTC
    - cron: '0 0 * * FRI'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: yuanw-nix-home-macos
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Update flake.lock
      uses: DeterminateSystems/update-flake-lock@v24
      with:
        pr-title: "Update flake.lock" # Title of PR to be created
        pr-labels: |                  # Labels to be set on the PR
          automated    - run: GITHUB_PATH= nix flake update
